dist: trusty
sudo: required
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test
